### ISSUE TITLE
Design how a user can amend a submitted declaration

### ISSUE THREAD

**Issue by GrilloPress** [samanthasaw/nhs-edec#12]
If a user needs to amend their declaration before the final submission date, they should be able to amend the submission.

The system should also log this request.

Design a high level flow of how this should work

**Comment by samanthasaw** [comment]
Users could get confused by 'see your previously submitted electronic declarations' and think they should go here instead of going into the practice page. 

So, the previously submitted section should allow users to reopen a submitted eDec as well as if the user were to go into the practice page. Both should handle allowing users to reopen a submitted eDec

**Comment by samanthasaw** [comment]
![reopen submission flow](https://user-images.githubusercontent.com/38656667/62143486-f9d22880-b2e7-11e9-9891-6cdc4c39504a.JPG)

**Comment by samanthasaw** [comment]
Explore having an updated tag, so section complete says 'you've updated this section'
Then the tag on the task list says: 'Updated'
